### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [55]:
import numpy as np
import copy

def swapping(x):
    x1,x5=copy.deepcopy(x[0]),copy.deepcopy(x[4])
    x[4]=x1
    x[0]=x5
    return x

x = np.random.randint(1,10,(5,5))
print(x)
print(swapping(x))

[[2 8 8 2 4]
 [6 6 8 5 9]
 [5 1 4 5 2]
 [4 6 2 3 2]
 [8 8 5 7 2]]
[[8 8 5 7 2]
 [6 6 8 5 9]
 [5 1 4 5 2]
 [4 6 2 3 2]
 [2 8 8 2 4]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [59]:
def removezero(x):
    y = np.array([row for row in x if 0 not in row])
    return y
    
x = np.random.randint(-5,5,(5,5))
print(x)
print(removezero(x))
     

[[-5 -1 -1  4 -3]
 [-1 -3 -5 -5 -4]
 [ 2  2 -2 -5  4]
 [ 0 -1  0 -1  2]
 [ 0 -3  4  1  3]]
[[-5 -1 -1  4 -3]
 [-1 -3 -5 -5 -4]
 [ 2  2 -2 -5  4]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [74]:
def realpart(x):
    real = []
    for i in x:
        s = str(i).split('+')
        real.append(float(s[0].replace("(","")))
    return np.array(real)
def imaginarypart(x):
    imaginary = []
    for i in x:
        s = str(i).split('+')
        imaginary.append(float(s[1].replace("j)","")))
    return np.array(imaginary)

x = np.array([1.00000000+0.j ,0.70710678+0.70710678j])
print(realpart(x))
print(imaginarypart(x))



[1.         0.70710678]
[0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [75]:
def unique(x):
    y = []
    for i in x:
        if i not in y:
            y.append(i)
    return y

x = np.array([10, 10, 20, 20, 30, 30])
print(unique(x))


[10, 20, 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [36]:
x = np.random.random((3,3,3))
print(x)

[[[0.89301369 0.72036118 0.02603921]
  [0.06924948 0.87722974 0.20114354]
  [0.7760936  0.10607563 0.80291036]]

 [[0.78452371 0.02844093 0.62194927]
  [0.05131911 0.36675713 0.84458089]
  [0.98733866 0.75822756 0.458203  ]]

 [[0.25948158 0.74858936 0.72287592]
  [0.68625567 0.35632732 0.13344518]
  [0.18552922 0.00398124 0.50216006]]]


### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [86]:
def sorting(x):
    print(x)
    for i in range(0,len(x)):
        for j in range(0,len(x)):
            if x[i]<x[j]:
                yo=x[j]
                x[j]=x[i]
                x[i]=yo
    print(x)

x=np.random.randint(20,size=(10))
sorting(x)

[ 8 19  4 17 15 15  6 19 14 15]
[ 4  6  8 14 15 15 15 17 19 19]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [78]:
def equalitycheck(x,y):
    n = len(x)
    result = True
    for i in range(n):
        if (x[i]!=y[i]):
            result = False
            break
    return result
        
x = np.random.random(10)
y = np.random.random(10)
print(x)
print(y)
print(f"Equal = {equalitycheck(x,y)}")

[0.45571721 0.15262845 0.42835021 0.20483084 0.36143479 0.14470571
 0.51228317 0.55314714 0.96434157 0.33251256]
[0.17896018 0.43736999 0.38695773 0.75793955 0.09460095 0.06675258
 0.75416208 0.60016808 0.347761   0.56309565]
Equal = False


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [87]:
x = np.array([[10,40],[30,20]])
x = np.array(sorted(x.flatten())).reshape(2,2)
print(x)


[[10 20]
 [30 40]]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [82]:
def floor(x):
    fl = []
    for i in x:
        if i >= 0:
            fl.append(int(i))
        else:
            fl.append(int(i) - 1)
    return np.array(fl)
def ceiling(x):
    cl = []
    for i in x:
        if i >= 0:
            cl.append(int(i) + 1)
        else:
            cl.append(int(i))
    return np.array(cl)
def truncated(x):
    tr = [int(i) for i in x]
    return np.array(tr)

x = np.array([-1.6,1.5,-0.3,0.1,1.4,1.8,2. ])
print(f"{floor(x)}\n{ceiling(x)}\n{truncated(x)}")

[-2  1 -1  0  1  1  2]
[-1  2  0  1  2  2  3]
[-1  1  0  0  1  1  2]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [2]:
start_date = np.datetime64('2017-03-01')
end_date = np.datetime64('2017-04-01')
dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(dates)


['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [1]:
import numpy as np
import datetime

start_datetime = np.datetime64('2000-01-01T00:00')
end_datetime = np.datetime64('2000-01-02T00:00')

datetime_objects = np.arange(start_datetime, end_datetime, dtype='datetime64[h]')

formatted_output = [datetime.datetime.utcfromtimestamp(dt.astype(int)) for dt in datetime_objects]

print(formatted_output)

[datetime.datetime(1970, 1, 4, 1, 2, 48), datetime.datetime(1970, 1, 4, 1, 2, 49), datetime.datetime(1970, 1, 4, 1, 2, 50), datetime.datetime(1970, 1, 4, 1, 2, 51), datetime.datetime(1970, 1, 4, 1, 2, 52), datetime.datetime(1970, 1, 4, 1, 2, 53), datetime.datetime(1970, 1, 4, 1, 2, 54), datetime.datetime(1970, 1, 4, 1, 2, 55), datetime.datetime(1970, 1, 4, 1, 2, 56), datetime.datetime(1970, 1, 4, 1, 2, 57), datetime.datetime(1970, 1, 4, 1, 2, 58), datetime.datetime(1970, 1, 4, 1, 2, 59), datetime.datetime(1970, 1, 4, 1, 3), datetime.datetime(1970, 1, 4, 1, 3, 1), datetime.datetime(1970, 1, 4, 1, 3, 2), datetime.datetime(1970, 1, 4, 1, 3, 3), datetime.datetime(1970, 1, 4, 1, 3, 4), datetime.datetime(1970, 1, 4, 1, 3, 5), datetime.datetime(1970, 1, 4, 1, 3, 6), datetime.datetime(1970, 1, 4, 1, 3, 7), datetime.datetime(1970, 1, 4, 1, 3, 8), datetime.datetime(1970, 1, 4, 1, 3, 9), datetime.datetime(1970, 1, 4, 1, 3, 10), datetime.datetime(1970, 1, 4, 1, 3, 11)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [9]:
def concat(x,y):
    a = []
    n = len(x)
    for i in range(n):
        b = f"{x[i]} {y[i]}"
        a.append(b)
    print(np.array(a))

x = np.array(['Python','PHP'])
y = np.array(['Java','C++'])
concat(x,y)

['Python Java' 'PHP C++']
